apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend
spec:
  containers:
  - image: sahiljasoliya/node-web:1.1.1
    imagePullPolicy: Never
    name: nodewebapp
    ports:
    - containerPort: 3040
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  